version: '3.8'

services:
  event-broker-svc:
    build: .
    container_name: event-broker
    environment:
      NATS_URL: nats://nats:4222
    depends_on:
      - nats

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"